server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#jdbc:mysql://39.108.48.22:3306/bmofang?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
spring:
    application:
        name: eureka-client
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat,wall
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://39.108.48.22:3306/bmofang?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: bmofang
          password: java
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    #配置视图解析,自动为视图文件加上前后缀.
    mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp
##开启 sql+log日志   logging.leval+包名 (com.winterchen.dao)  +日志等级(debug)
#logging:
#  level:
#    com: debug
  ##将日志输出到当前工作目录下,file默认是以10MB为一个日志文件大小.
#  file: logs/my.log
#  pattern:
#    file: "%msg%n"

##开启mybatis经典数据库下划线命名转java驼峰命名
mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com.bmofang.mapper/*.xml
  type-aliases-package: com.bmofang.bean


