server:
  port: 8080
  servlet:
    context-path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://39.108.48.22:3306/bmofang?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: bmofang
    password: java
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #新增数据库链接的必备参数, 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新

##开启sql+log日志   logging.leval+包名 (com.winterchen.dao)  +日志等级(debug)
logging:
  level:
    com: debug

